# Generated by Django 2.2.13 on 2020-07-12 04:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_code', models.CharField(blank=True, max_length=50, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_updated', models.DateField(default=django.utils.timezone.now, verbose_name='Updated')),
            ],
        ),
    ]
