# Generated by Django 2.2.16 on 2020-09-15 20:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumReviewSession',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('pass_code', models.CharField(blank=True, max_length=50, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
            ],
        ),
    ]
