# Generated by Django 3.2.12 on 2022-02-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crtool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumreviewsession',
            name='data',
            field=models.JSONField(),
        ),
    ]
