# Generated by Django 3.2.12 on 2022-02-28 21:16

from django import VERSION
from django.db import migrations


if VERSION[0] < 3:
    from django.contrib.postgres.fields import JSONField
else:
    from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('crtool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumreviewsession',
            name='data',
            field=JSONField(),
        ),
    ]
