# Generated by Django 2.2.13 on 2020-08-17 02:27

import crtool.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crtool', '0002_auto_20200715_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumreviewsession',
            name='data',
            field=crtool.fields.JSONField(),
        ),
    ]
