# Generated by Django 2.2.13 on 2020-08-17 02:27

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration has been removed.
    """

    dependencies = [
        ('crtool', '0002_auto_20200715_2030'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop),
    ]
