# Generated by Django 2.2.13 on 2020-08-28 03:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crtool', '0003_use_custom_jsonfield_for_sqlite3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumreviewsession',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
