# Generated by Django 2.2.13 on 2020-08-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crtool', '0004_revert_back_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumreviewsession',
            name='id',
            field=models.CharField(editable=False, max_length=7, primary_key=True, serialize=False),
        ),
    ]
