# Generated by Django 2.2.16 on 2020-09-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crtool', '0005_change_id_from_uuid_to_short_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumreviewsession',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
