# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 17:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0019_activitybuildingblock_svg_icon_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='activityindexpage',
            name='header',
            field=wagtail.wagtailcore.fields.StreamField([('text_introduction', wagtail.wagtailcore.blocks.StructBlock([('eyebrow', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional: Adds an H5 eyebrow above H1 heading text. Only use in conjunction with heading.', label='Pre-heading', required=False)), ('heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('url', wagtail.wagtailcore.blocks.CharBlock(default='/', required=False))]), required=False)), ('has_rule', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Check this to add a horizontal rule line to bottom of text introduction.', label='Has bottom rule', required=False))]))], blank=True),
        ),
    ]
