# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 13:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0021_activityindexpage_image_squashed_0023_auto_20190503_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityindexpage',
            name='header_sidebar',
            field=wagtail.wagtailcore.fields.StreamField([('image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text=b'Should be exactly 390px tall, and up to 940px wide, unless this is an overlay or bleeding style hero.')), (b'small_image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text=b'Provide an alternate image for small displays when using a bleeding or overlay hero.', required=False))]))], blank=True),
        ),
    ]
